/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Calibrations */
        get: operations["list_calibrations_api_calibration_get"];
        put?: never;
        /** Upload Calibration */
        post: operations["upload_calibration_api_calibration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find */
        post: operations["find_api_find_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Images */
        get: operations["list_images_api_images_get"];
        put?: never;
        /** Upload Image */
        post: operations["upload_image_api_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/{tier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Tier */
        get: operations["get_image_tier_api_images__image_id___tier__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Measure */
        post: operations["measure_api_measure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_models_get"];
        put?: never;
        /** Create Model */
        post: operations["create_model_api_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rectify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rectify */
        post: operations["rectify_api_rectify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rectify/{image_id}/{model_id}/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Crop */
        get: operations["get_crop_api_rectify__image_id___model_id___index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_calibration_api_calibration_post */
        Body_upload_calibration_api_calibration_post: {
            /** File */
            file: string;
        };
        /** Body_upload_image_api_images_post */
        Body_upload_image_api_images_post: {
            /** File */
            file: string;
        };
        /** CalibrationOut */
        CalibrationOut: {
            /** Filename */
            filename: string;
            /**
             * Format
             * @enum {string}
             */
            format: "rig_extrinsics" | "table_calibration";
            /** Id */
            id: string;
            /** N Cameras */
            n_cameras: number;
        };
        /** CaliperProfileOut */
        CaliperProfileOut: {
            /** Edges */
            edges: components["schemas"]["EdgeMarkOut"][];
            /** Step Px */
            step_px: number;
            /** Values */
            values: number[];
        };
        /** CaliperResultOut */
        CaliperResultOut: {
            /** Index */
            index: number;
            profile: components["schemas"]["CaliperProfileOut"];
            /** Reason */
            reason?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "hit" | "rejected";
        };
        /**
         * CropSpecIn
         * @description Mirrors `vm.CropSpec`. `rect` is in **model-frame coordinates** — the
         *     taught model's own reference-image frame, i.e. the same coordinates as
         *     `ModelOut.roi` — so a sensible default is the taught model's own `roi`.
         */
        CropSpecIn: {
            /**
             * Normalize Scale
             * @description Render at model scale (True, canonical) or found scale (False).
             * @default true
             */
            normalize_scale: boolean;
            /**
             * Px Per Unit
             * @default 1
             */
            px_per_unit: number;
            /** Rect */
            rect: [
                number,
                number,
                number,
                number
            ];
        };
        /** EdgeMarkOut */
        EdgeMarkOut: {
            /** Polarity */
            polarity: string;
            /** Pos Px */
            pos_px: number;
            /** X Mm */
            x_mm?: number | null;
            /** Y Mm */
            y_mm?: number | null;
        };
        /** FindRequest */
        FindRequest: {
            /** Angle Range */
            angle_range?: [
                number,
                number
            ] | null;
            /** Image Id */
            image_id: string;
            /** Max Matches */
            max_matches?: number | null;
            /**
             * Min Score
             * @default 0.7
             */
            min_score: number;
            /** Model Id */
            model_id: string;
            /** Roi */
            roi?: [
                number,
                number,
                number,
                number
            ] | null;
        };
        /** FindResponse */
        FindResponse: {
            /** Matches */
            matches: components["schemas"]["MatchOut"][];
        };
        /**
         * FitConfigIn
         * @description Overrides for `vm.FitConfig`.
         */
        FitConfigIn: {
            /** Inlier Tol */
            inlier_tol?: number | null;
            /** Loss */
            loss?: ("l2" | "huber" | "tukey") | null;
        };
        /** FixtureIn */
        FixtureIn: {
            /**
             * Angle
             * @default 0
             */
            angle: number;
            /**
             * Scale
             * @default 1
             */
            scale: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageOut */
        ImageOut: {
            /** Filename */
            filename: string;
            /** Height */
            height: number;
            /** Id */
            id: string;
            /** Sha256 */
            sha256: string;
            /** Width */
            width: number;
        };
        /** MatchOut */
        MatchOut: {
            /** Angle */
            angle: number;
            /** Level */
            level: number;
            /** Scale */
            scale: number;
            /** Score */
            score: number;
            /** Support */
            support: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * MeasureConfigIn
         * @description Overrides for `vm.MeasureConfig`; unset fields fall back to library defaults.
         */
        MeasureConfigIn: {
            /** Max Obliquity Deg */
            max_obliquity_deg?: number | null;
            /** Polarity */
            polarity?: ("bright_to_dark" | "dark_to_bright" | "either") | null;
            /** Sigma */
            sigma?: number | null;
            /** Threshold */
            threshold?: number | null;
        };
        /**
         * MeasureObjectIn
         * @description One metrology object, nominal geometry given in **model frame** (the taught
         *     `ShapeModel`'s own coordinates, i.e. relative to its `origin`).
         */
        MeasureObjectIn: {
            /** Arc */
            arc?: [
                number,
                number
            ] | null;
            /** Ax */
            ax?: number | null;
            /** Ay */
            ay?: number | null;
            /** Bx */
            bx?: number | null;
            /** By */
            by?: number | null;
            /**
             * Caliper Len
             * @default 20
             */
            caliper_len: number;
            /**
             * Caliper Width
             * @default 8
             */
            caliper_width: number;
            /** Cx */
            cx?: number | null;
            /** Cy */
            cy?: number | null;
            fit?: components["schemas"]["FitConfigIn"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "circle" | "line";
            /** Label */
            label?: string | null;
            measure?: components["schemas"]["MeasureConfigIn"];
            /**
             * N Calipers
             * @default 12
             */
            n_calipers: number;
            /** R */
            r?: number | null;
        };
        /** MeasureObjectResultOut */
        MeasureObjectResultOut: {
            /** Calipers */
            calipers?: components["schemas"]["CaliperResultOut"][];
            /** Circle Cx */
            circle_cx?: number | null;
            /** Circle Cx Mm */
            circle_cx_mm?: number | null;
            /** Circle Cy */
            circle_cy?: number | null;
            /** Circle Cy Mm */
            circle_cy_mm?: number | null;
            /** Circle R */
            circle_r?: number | null;
            /** Circle R Mm */
            circle_r_mm?: number | null;
            /** Kind */
            kind: ("circle" | "line") | "error";
            /** Label */
            label?: string | null;
            /** Line Dx */
            line_dx?: number | null;
            /** Line Dy */
            line_dy?: number | null;
            /** Line Px */
            line_px?: number | null;
            /** Line Py */
            line_py?: number | null;
            /** Max Dev */
            max_dev?: number | null;
            /** Message */
            message?: string | null;
            /** N Used */
            n_used?: number | null;
            /** Overlay */
            overlay?: components["schemas"]["OverlayPrimitiveOut"][];
            /** Rms */
            rms?: number | null;
        };
        /** MeasureRequest */
        MeasureRequest: {
            /**
             * Calibration Id
             * @description When set, the response is augmented with millimetre values (pixel_to_plane over the calibration's camera_index camera and plane).
             */
            calibration_id?: string | null;
            /**
             * Camera Index
             * @description Index into the calibration's camera list.
             * @default 0
             */
            camera_index: number;
            fixture?: components["schemas"]["FixtureIn"] | null;
            /** Image Id */
            image_id: string;
            /**
             * Min Score
             * @default 0.7
             */
            min_score: number;
            /** Model Id */
            model_id: string;
            /** Objects */
            objects: components["schemas"]["MeasureObjectIn"][];
            plane?: components["schemas"]["PlaneIn"];
        };
        /** MeasureResponse */
        MeasureResponse: {
            fixture: components["schemas"]["FixtureIn"];
            /**
             * Fixture Source
             * @enum {string}
             */
            fixture_source: "explicit" | "auto_find";
            /** Objects */
            objects: components["schemas"]["MeasureObjectResultOut"][];
        };
        /** ModelCreateRequest */
        ModelCreateRequest: {
            /** Image Id */
            image_id: string;
            /**
             * Min Contrast
             * @description fraction of dtype range
             * @default 0.1
             */
            min_contrast: number;
            /** Num Levels */
            num_levels?: number | null;
            /** Roi */
            roi: [
                number,
                number,
                number,
                number
            ];
        };
        /** ModelOut */
        ModelOut: {
            /** Id */
            id: string;
            /** Image Id */
            image_id: string;
            /** Min Contrast */
            min_contrast: number;
            /** Num Levels */
            num_levels: number | null;
            /** Num Levels Built */
            num_levels_built: number;
            /** Origin */
            origin: [
                number,
                number
            ];
            /** Point Counts */
            point_counts: number[];
            /** Roi */
            roi: [
                number,
                number,
                number,
                number
            ];
        };
        /**
         * OverlayPrimitiveOut
         * @description Mirrors `@vitavision/lab-ui`'s `MeasurePrimitive` union exactly (field names and
         *     units — angles in radians) so the frontend can pass this straight through.
         */
        OverlayPrimitiveOut: {
            /** Angle */
            angle?: number | null;
            /** Cross */
            cross?: boolean | null;
            /** Cx */
            cx?: number | null;
            /** Cy */
            cy?: number | null;
            /** Dashed */
            dashed?: boolean | null;
            /** Endangle */
            endAngle?: number | null;
            /** Height */
            height?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "point" | "segment" | "circle" | "arc" | "caliper" | "dimension";
            /** Label */
            label?: string | null;
            /** R */
            r?: number | null;
            /** Startangle */
            startAngle?: number | null;
            /** Tone */
            tone?: ("signal" | "normal" | "defect" | "warn" | "muted") | null;
            /** Width */
            width?: number | null;
            /** X */
            x?: number | null;
            /** X1 */
            x1?: number | null;
            /** X2 */
            x2?: number | null;
            /** Y */
            y?: number | null;
            /** Y1 */
            y1?: number | null;
            /** Y2 */
            y2?: number | null;
        };
        /**
         * PlaneIn
         * @description A plane in the calibration's reference frame: `n . X + d = 0`. Defaults to the
         *     rig/table frame's own `z = 0` plane — the common case (a flat stage/conveyor).
         */
        PlaneIn: {
            /**
             * D
             * @default 0
             */
            d: number;
            /**
             * Nx
             * @default 0
             */
            nx: number;
            /**
             * Ny
             * @default 0
             */
            ny: number;
            /**
             * Nz
             * @default 1
             */
            nz: number;
        };
        /** RectifyMatchOut */
        RectifyMatchOut: {
            /** Angle */
            angle: number;
            /** Crop Url */
            crop_url: string;
            /** Height */
            height: number;
            /** Index */
            index: number;
            /** Level */
            level: number;
            /** Scale */
            scale: number;
            /** Score */
            score: number;
            /** Support */
            support: number;
            /**
             * Validity
             * @description fraction of crop pixels sampled from inside the scene
             */
            validity: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** RectifyRequest */
        RectifyRequest: {
            crop: components["schemas"]["CropSpecIn"];
            /** Image Id */
            image_id: string;
            /** Max Matches */
            max_matches?: number | null;
            /**
             * Min Score
             * @default 0.7
             */
            min_score: number;
            /** Model Id */
            model_id: string;
        };
        /** RectifyResponse */
        RectifyResponse: {
            /** Height */
            height: number;
            /** Matches */
            matches: components["schemas"]["RectifyMatchOut"][];
            /** Width */
            width: number;
        };
        /**
         * Tier
         * @enum {string}
         */
        Tier: "thumb" | "preview" | "full";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_calibrations_api_calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationOut"][];
                };
            };
        };
    };
    upload_calibration_api_calibration_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_calibration_api_calibration_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_api_find_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_images_api_images_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"][];
                };
            };
        };
    };
    upload_image_api_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_tier_api_images__image_id___tier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
                tier: components["schemas"]["Tier"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    measure_api_measure_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"][];
                };
            };
        };
    };
    create_model_api_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rectify_api_rectify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RectifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RectifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crop_api_rectify__image_id___model_id___index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
                model_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
